-- Promote weekly_hours_reviews into the canonical, versioned weekly timesheet.
-- Raw submissions remain in hours_entries / cts_hours_import_rows, while only a
-- locked snapshot is eligible to become a payroll or invoicing source.

alter table public.weekly_hours_reviews
  drop constraint if exists weekly_hours_reviews_status_check;

alter table public.weekly_hours_reviews
  add constraint weekly_hours_reviews_status_check
  check (status in (
    'draft', 'pending', 'submitted', 'disputed', 'reviewed', 'approved', 'locked',
    'correction_requested'
  ));

alter table public.weekly_hours_reviews
  add column if not exists official_source text
    check (official_source in ('admin', 'worker', 'cts')),
  add column if not exists version integer not null default 1 check (version > 0),
  add column if not exists regular_hours numeric(8,2) not null default 0 check (regular_hours >= 0),
  add column if not exists overtime_hours numeric(8,2) not null default 0 check (overtime_hours >= 0),
  add column if not exists double_time_hours numeric(8,2) not null default 0 check (double_time_hours >= 0),
  add column if not exists submitted_at timestamptz,
  add column if not exists submitted_by uuid references auth.users(id) on delete set null,
  add column if not exists locked_at timestamptz,
  add column if not exists locked_by uuid references auth.users(id) on delete set null,
  add column if not exists locked_snapshot jsonb,
  add column if not exists reconciliation jsonb not null default '{}'::jsonb,
  add column if not exists correction_reason text;

create index if not exists weekly_hours_reviews_locked_idx
  on public.weekly_hours_reviews (week_start_date, locked_at)
  where status = 'locked';

create table if not exists public.timesheet_events (
  id bigint generated by default as identity primary key,
  timesheet_id uuid not null references public.weekly_hours_reviews(id) on delete cascade,
  version integer not null check (version > 0),
  event_type text not null check (event_type in (
    'created', 'submitted', 'edited', 'reviewed', 'disputed', 'locked',
    'correction_requested', 'cleared', 'imported'
  )),
  actor_id uuid references auth.users(id) on delete set null default auth.uid(),
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists timesheet_events_timesheet_created_idx
  on public.timesheet_events (timesheet_id, created_at desc);

create table if not exists public.timesheet_exceptions (
  id uuid primary key default gen_random_uuid(),
  timesheet_id uuid not null references public.weekly_hours_reviews(id) on delete cascade,
  exception_type text not null check (exception_type in (
    'source_mismatch', 'daily_limit', 'weekly_overtime', 'late_submission', 'missing_hours'
  )),
  severity text not null default 'warning' check (severity in ('warning', 'blocking')),
  details jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  resolution_notes text,
  created_at timestamptz not null default now()
);

create index if not exists timesheet_exceptions_open_idx
  on public.timesheet_exceptions (timesheet_id, severity)
  where resolved_at is null;

create unique index if not exists timesheet_exceptions_one_open_type_idx
  on public.timesheet_exceptions (timesheet_id, exception_type)
  where resolved_at is null;

alter table public.timesheet_events enable row level security;
alter table public.timesheet_exceptions enable row level security;

revoke all on public.timesheet_events from anon;
revoke all on public.timesheet_exceptions from anon;
grant select, insert on public.timesheet_events to authenticated;
grant select, insert, update on public.timesheet_exceptions to authenticated;

drop policy if exists "Admins can read timesheet events" on public.timesheet_events;
create policy "Admins can read timesheet events"
on public.timesheet_events for select to authenticated
using ((select public.can_manage_cts_jobs()));

drop policy if exists "Admins can create timesheet events" on public.timesheet_events;
create policy "Admins can create timesheet events"
on public.timesheet_events for insert to authenticated
with check ((select public.can_manage_cts_jobs()));

drop policy if exists "Admins can read timesheet exceptions" on public.timesheet_exceptions;
create policy "Admins can read timesheet exceptions"
on public.timesheet_exceptions for select to authenticated
using ((select public.can_manage_cts_jobs()));

drop policy if exists "Admins can create timesheet exceptions" on public.timesheet_exceptions;
create policy "Admins can create timesheet exceptions"
on public.timesheet_exceptions for insert to authenticated
with check ((select public.can_manage_cts_jobs()));

drop policy if exists "Admins can resolve timesheet exceptions" on public.timesheet_exceptions;
create policy "Admins can resolve timesheet exceptions"
on public.timesheet_exceptions for update to authenticated
using ((select public.can_manage_cts_jobs()))
with check ((select public.can_manage_cts_jobs()));

create or replace function public.guard_locked_hours_entries()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_candidate_id uuid := coalesce(new.cts_job_candidate_id, old.cts_job_candidate_id);
  v_week_start date := coalesce(new.week_start_date, old.week_start_date);
begin
  if exists (
    select 1 from public.weekly_hours_reviews r
    where r.cts_job_candidate_id = v_candidate_id
      and r.week_start_date = v_week_start
      and r.status = 'locked'
  ) then
    raise exception 'This timesheet is locked. Use the correction workflow before editing hours.';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_locked_hours_entries on public.hours_entries;
create trigger trg_guard_locked_hours_entries
before insert or update or delete on public.hours_entries
for each row execute function public.guard_locked_hours_entries();

create or replace function public.track_worker_timesheet_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_candidate_id uuid := coalesce(new.cts_job_candidate_id, old.cts_job_candidate_id);
  v_job_id uuid := coalesce(new.cts_job_id, old.cts_job_id);
  v_worker_id uuid := coalesce(new.worker_id, old.worker_id);
  v_week_start date := coalesce(new.week_start_date, old.week_start_date);
  v_source text := coalesce(new.source, old.source);
  v_timesheet public.weekly_hours_reviews%rowtype;
begin
  if v_source <> 'client' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  insert into public.weekly_hours_reviews (
    cts_job_candidate_id, cts_job_id, worker_id, week_start_date,
    status, submitted_at, submitted_by
  ) values (
    v_candidate_id, v_job_id, v_worker_id, v_week_start,
    'submitted', now(), auth.uid()
  )
  on conflict (cts_job_candidate_id, week_start_date)
  do update set status = 'submitted', submitted_at = now(), submitted_by = auth.uid(),
    reviewed_at = null, reviewed_by = null, approved_at = null, approved_by = null
  where public.weekly_hours_reviews.status <> 'locked'
  returning * into v_timesheet;

  if v_timesheet.id is not null then
    insert into public.timesheet_events (timesheet_id, version, event_type, payload)
    values (v_timesheet.id, v_timesheet.version, 'submitted',
      jsonb_build_object('source', 'worker', 'operation', tg_op));
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_track_worker_timesheet_submission on public.hours_entries;
create trigger trg_track_worker_timesheet_submission
after insert or update or delete on public.hours_entries
for each row execute function public.track_worker_timesheet_submission();

create or replace function public.normalize_legacy_timesheet_status()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Legacy CTS import RPCs used "approved" to mean "received from CTS".
  -- Keep those RPC signatures compatible while separating import from approval.
  if new.status = 'approved'
     and coalesce(new.notes, '') like 'Approved from CTS spreadsheet import:%' then
    new.status := 'submitted';
    new.submitted_at := now();
    new.submitted_by := auth.uid();
    new.reviewed_at := null;
    new.reviewed_by := null;
    new.approved_at := null;
    new.approved_by := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_normalize_legacy_timesheet_status on public.weekly_hours_reviews;
create trigger trg_normalize_legacy_timesheet_status
before insert or update on public.weekly_hours_reviews
for each row execute function public.normalize_legacy_timesheet_status();

create or replace function public.save_admin_weekly_timesheet(
  p_candidate_id uuid,
  p_week_start date,
  p_entries jsonb,
  p_reason text default null
)
returns public.weekly_hours_reviews
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_candidate public.cts_job_candidates%rowtype;
  v_timesheet public.weekly_hours_reviews%rowtype;
  v_item jsonb;
  v_date date;
  v_hours numeric;
begin
  if not (select public.can_manage_cts_jobs()) then
    raise exception 'Only administrators can edit weekly timesheets';
  end if;
  if date_trunc('week', p_week_start)::date <> p_week_start then
    raise exception 'Week start must be a Monday';
  end if;
  if jsonb_typeof(coalesce(p_entries, '[]'::jsonb)) <> 'array' then
    raise exception 'Entries must be a JSON array';
  end if;

  select * into strict v_candidate
  from public.cts_job_candidates
  where id = p_candidate_id;

  insert into public.weekly_hours_reviews (
    cts_job_candidate_id, cts_job_id, worker_id, week_start_date, status
  ) values (
    v_candidate.id, v_candidate.cts_job_id, v_candidate.worker_id, p_week_start, 'draft'
  )
  on conflict (cts_job_candidate_id, week_start_date) do nothing;

  select * into v_timesheet
  from public.weekly_hours_reviews
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start
  for update;

  if v_timesheet.status = 'locked' then
    if coalesce(trim(p_reason), '') = '' then
      raise exception 'A correction reason is required to change a locked timesheet';
    end if;
    insert into public.timesheet_events (timesheet_id, version, event_type, reason, payload)
    values (v_timesheet.id, v_timesheet.version, 'correction_requested', trim(p_reason),
      jsonb_build_object('locked_snapshot', v_timesheet.locked_snapshot));
    update public.weekly_hours_reviews
    set status = 'correction_requested', version = version + 1,
        correction_reason = trim(p_reason), official_source = null,
        locked_at = null, locked_by = null, locked_snapshot = null,
        approved_at = null, approved_by = null
    where id = v_timesheet.id
    returning * into v_timesheet;
  end if;

  delete from public.hours_entries
  where cts_job_candidate_id = p_candidate_id
    and source = 'admin'
    and work_date between p_week_start and p_week_start + 6;

  for v_item in select value from jsonb_array_elements(coalesce(p_entries, '[]'::jsonb)) loop
    v_date := (v_item->>'work_date')::date;
    v_hours := nullif(v_item->>'regular_hours', '')::numeric;
    if v_date < p_week_start or v_date > p_week_start + 6 then
      raise exception 'Entry date % is outside the selected week', v_date;
    end if;
    if v_hours is not null and (v_hours < 0 or v_hours > 24) then
      raise exception 'Daily hours must be between 0 and 24';
    end if;
    if coalesce(v_hours, 0) > 0 then
      insert into public.hours_entries (
        cts_job_candidate_id, cts_job_id, worker_id, work_date,
        week_start_date, source, regular_hours, notes
      ) values (
        v_candidate.id, v_candidate.cts_job_id, v_candidate.worker_id, v_date,
        p_week_start, 'admin', v_hours, nullif(trim(p_reason), '')
      );
    end if;
  end loop;

  update public.weekly_hours_reviews
  set status = 'draft', reviewed_at = null, reviewed_by = null,
      approved_at = null, approved_by = null, official_source = null,
      regular_hours = 0, overtime_hours = 0, double_time_hours = 0,
      reconciliation = '{}'::jsonb
  where id = v_timesheet.id
  returning * into v_timesheet;

  insert into public.timesheet_events (timesheet_id, version, event_type, reason, payload)
  values (v_timesheet.id, v_timesheet.version, 'edited', nullif(trim(p_reason), ''),
    jsonb_build_object('source', 'admin', 'entries', coalesce(p_entries, '[]'::jsonb)));
  return v_timesheet;
end;
$$;

create or replace function public.review_weekly_timesheet(
  p_candidate_id uuid,
  p_week_start date,
  p_action text,
  p_official_source text default null,
  p_reason text default null
)
returns public.weekly_hours_reviews
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_candidate public.cts_job_candidates%rowtype;
  v_timesheet public.weekly_hours_reviews%rowtype;
  v_admin numeric := 0;
  v_worker numeric := 0;
  v_cts_regular numeric := 0;
  v_cts_ot numeric := 0;
  v_cts_dt numeric := 0;
  v_selected numeric := 0;
  v_difference numeric := 0;
  v_snapshot jsonb := '[]'::jsonb;
begin
  if not (select public.can_manage_cts_jobs()) then
    raise exception 'Only administrators can review weekly timesheets';
  end if;
  if p_action not in ('reviewed', 'disputed', 'locked') then
    raise exception 'Unsupported timesheet action';
  end if;
  if p_action = 'disputed' and coalesce(trim(p_reason), '') = '' then
    raise exception 'A dispute reason is required';
  end if;

  select * into strict v_candidate from public.cts_job_candidates where id = p_candidate_id;
  insert into public.weekly_hours_reviews (
    cts_job_candidate_id, cts_job_id, worker_id, week_start_date, status
  ) values (v_candidate.id, v_candidate.cts_job_id, v_candidate.worker_id, p_week_start, 'draft')
  on conflict (cts_job_candidate_id, week_start_date) do nothing;

  select * into v_timesheet from public.weekly_hours_reviews
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start
  for update;

  if v_timesheet.status = 'locked' then
    raise exception 'This timesheet is locked. Request a correction before changing it.';
  end if;

  select coalesce(sum(regular_hours), 0) into v_admin from public.hours_entries
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start and source = 'admin';
  select coalesce(sum(regular_hours), 0) into v_worker from public.hours_entries
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start and source = 'client';
  select coalesce(sum(regular_hours), 0), coalesce(sum(overtime_hours), 0), coalesce(sum(double_time_hours), 0)
  into v_cts_regular, v_cts_ot, v_cts_dt from public.cts_hours_import_rows
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start;

  if p_action = 'locked' then
    if p_official_source not in ('admin', 'worker', 'cts') then
      raise exception 'Choose admin, worker, or CTS as the official source';
    end if;
    if p_official_source = 'admin' then v_selected := v_admin;
    elsif p_official_source = 'worker' then v_selected := v_worker;
    else v_selected := v_cts_regular + v_cts_ot + v_cts_dt;
    end if;
    if v_selected <= 0 then raise exception 'The selected source has no hours'; end if;

    select coalesce(max(value) - min(value), 0) into v_difference
    from unnest(array_remove(array[
      case when v_admin > 0 then v_admin end,
      case when v_worker > 0 then v_worker end,
      case when v_cts_regular + v_cts_ot + v_cts_dt > 0 then v_cts_regular + v_cts_ot + v_cts_dt end
    ], null)) value;
    if v_difference > 0.25 and coalesce(trim(p_reason), '') = '' then
      raise exception 'The reported sources differ by % hours. Add an approval reason.', v_difference;
    end if;

    if p_official_source in ('admin', 'worker') then
      select coalesce(jsonb_agg(jsonb_build_object(
        'work_date', work_date, 'regular_hours', regular_hours
      ) order by work_date), '[]'::jsonb) into v_snapshot
      from public.hours_entries
      where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start
        and source = case when p_official_source = 'worker' then 'client' else 'admin' end;
    else
      select coalesce(jsonb_agg(to_jsonb(rows) order by source_row_key), '[]'::jsonb) into v_snapshot
      from (
        select source_row_key, source_employee_name, source_invoice_number,
          regular_hours, overtime_hours, double_time_hours
        from public.cts_hours_import_rows
        where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start
      ) rows;
    end if;

    update public.timesheet_exceptions set resolved_at = now(), resolved_by = auth.uid(),
      resolution_notes = coalesce(nullif(trim(p_reason), ''), 'Resolved during approval')
    where timesheet_id = v_timesheet.id and resolved_at is null;
    if v_difference > 0.25 then
      insert into public.timesheet_exceptions (
        timesheet_id, exception_type, severity, details, resolved_at, resolved_by, resolution_notes
      ) values (v_timesheet.id, 'source_mismatch', 'warning',
        jsonb_build_object('admin', v_admin, 'worker', v_worker, 'cts', v_cts_regular + v_cts_ot + v_cts_dt, 'difference', v_difference),
        now(), auth.uid(), trim(p_reason));
    end if;

    update public.weekly_hours_reviews set
      status = 'locked', official_source = p_official_source,
      regular_hours = case when p_official_source = 'cts' then v_cts_regular else least(v_selected, 40) end,
      overtime_hours = case when p_official_source = 'cts' then v_cts_ot else greatest(v_selected - 40, 0) end,
      double_time_hours = case when p_official_source = 'cts' then v_cts_dt else 0 end,
      approved_at = now(), approved_by = auth.uid(), locked_at = now(), locked_by = auth.uid(),
      locked_snapshot = jsonb_build_object('source', p_official_source, 'entries', v_snapshot),
      reconciliation = jsonb_build_object('admin', v_admin, 'worker', v_worker,
        'cts', v_cts_regular + v_cts_ot + v_cts_dt, 'difference', v_difference),
      notes = coalesce(nullif(trim(p_reason), ''), notes)
    where id = v_timesheet.id returning * into v_timesheet;
  else
    update public.weekly_hours_reviews set status = p_action,
      reviewed_at = case when p_action = 'reviewed' then now() else reviewed_at end,
      reviewed_by = case when p_action = 'reviewed' then auth.uid() else reviewed_by end,
      notes = coalesce(nullif(trim(p_reason), ''), notes)
    where id = v_timesheet.id returning * into v_timesheet;
  end if;

  insert into public.timesheet_events (timesheet_id, version, event_type, reason, payload)
  values (v_timesheet.id, v_timesheet.version, p_action, nullif(trim(p_reason), ''),
    jsonb_build_object('official_source', p_official_source, 'reconciliation', v_timesheet.reconciliation,
      'snapshot', v_timesheet.locked_snapshot));
  return v_timesheet;
end;
$$;

create or replace function public.clear_weekly_timesheet(
  p_candidate_id uuid, p_week_start date, p_reason text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare v_timesheet public.weekly_hours_reviews%rowtype;
begin
  if not (select public.can_manage_cts_jobs()) then raise exception 'Only administrators can clear timesheets'; end if;
  if coalesce(trim(p_reason), '') = '' then raise exception 'A reason is required'; end if;
  select * into v_timesheet from public.weekly_hours_reviews
  where cts_job_candidate_id = p_candidate_id and week_start_date = p_week_start for update;
  if v_timesheet.id is not null then
    insert into public.timesheet_events (timesheet_id, version, event_type, reason, payload)
    values (v_timesheet.id, v_timesheet.version, 'cleared', trim(p_reason),
      jsonb_build_object('previous_snapshot', v_timesheet.locked_snapshot));
    if v_timesheet.status = 'locked' then
      update public.weekly_hours_reviews
      set status = 'correction_requested', correction_reason = trim(p_reason)
      where id = v_timesheet.id;
    end if;
  end if;
  delete from public.hours_entries where cts_job_candidate_id = p_candidate_id
    and work_date between p_week_start and p_week_start + 6;
  delete from public.cts_hours_import_rows where cts_job_candidate_id = p_candidate_id
    and week_start_date = p_week_start;
  if v_timesheet.id is not null then
    update public.weekly_hours_reviews set status = 'draft', version = version + 1,
      official_source = null, regular_hours = 0, overtime_hours = 0, double_time_hours = 0,
      reviewed_at = null, reviewed_by = null, approved_at = null, approved_by = null,
      locked_at = null, locked_by = null, locked_snapshot = null,
      reconciliation = '{}'::jsonb, correction_reason = trim(p_reason)
    where id = v_timesheet.id;
  end if;
end;
$$;

revoke all on function public.save_admin_weekly_timesheet(uuid, date, jsonb, text) from public, anon;
revoke all on function public.review_weekly_timesheet(uuid, date, text, text, text) from public, anon;
revoke all on function public.clear_weekly_timesheet(uuid, date, text) from public, anon;
grant execute on function public.save_admin_weekly_timesheet(uuid, date, jsonb, text) to authenticated;
grant execute on function public.review_weekly_timesheet(uuid, date, text, text, text) to authenticated;
grant execute on function public.clear_weekly_timesheet(uuid, date, text) to authenticated;

-- Existing approved rows represented the old terminal state. Preserve their
-- approvals as locked snapshots at migration time.
update public.weekly_hours_reviews r
set status = 'locked', official_source = coalesce(
      case when exists (select 1 from public.cts_hours_import_rows c where c.cts_job_candidate_id = r.cts_job_candidate_id and c.week_start_date = r.week_start_date) then 'cts' end,
      case when exists (select 1 from public.hours_entries h where h.cts_job_candidate_id = r.cts_job_candidate_id and h.week_start_date = r.week_start_date and h.source = 'admin') then 'admin' end,
      'worker'
    ),
    locked_at = coalesce(r.approved_at, r.updated_at, now()),
    locked_by = r.approved_by,
    locked_snapshot = jsonb_build_object('legacy_approval', true, 'migrated_at', now())
where r.status = 'approved';

notify pgrst, 'reload schema';
